name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.1-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91ab2c704a1fd5696af7f17a57e9cc67f1d4d8f9fa45b1d78d002746a34646f8"

[versions]
fabric = "0.16.8"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
