name = "Client+"
author = "Thijzert"
version = "1.2.0+1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "342e3773af33a6f3cba7724218f4873bc78fe81862db60e31f4b20173ade42e4"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
