name = "Client+"
author = "Thijzert"
version = "1.0.1+1.21.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cad72d1721c5b03b6a918e67b81e20b64d1400d623a76f730977746a775acde6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
