name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.5-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0041a93922b0e6438a0a1eca01cde8d50fb82ef4a6422112a9272baa45fb7613"

[versions]
fabric = "0.16.10"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
