name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.5-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29ede769ee4456d21daaf0cb60aba4bba33ea364e13acb461b790992d20d83a7"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
