name = "Client+"
author = "Thijzert"
version = "1.1.0+1.21.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e4655b5c6649a19ee65bdadd0e32cd05de7854e3d85506b466189145e1b87b1"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
