name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.5-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "663ec9e0c1c0ac2c45e2db5675d1b15d4692525218bd0975f0d75e2d661ee322"

[versions]
fabric = "0.16.10"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
