name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.5-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78dbff7e3a8215aecb718842d3ce68322871f5b70bd3b6e455ccc912fe83e079"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
