# if none are set, everything is included
# include: ONLY use this project for these versions
# exclude: use this project for all versions EXCEPT for these
# include and exclude can't be used at the same time
#
# EXAMPLE:
# {
#     "mods":               [{"id": "yosbr",
#                                 "include": ["x.x.x", "x.x.x"]},
#                             {"id": "moreculling",
#                                 "exclude": ["x.x.x", "x.x.x"]}],

#     "shaderpacks":        ["makeup-ultra-fast-shaders",
#                            "bliss-shader"],

#     "resourcepacks":      ["default-splashes",
#                            "spawned-eggs"]
# }

{
    "mods": [
        {"id": "yosbr"},
        {"id": "moreculling"},
        {"id": "modmenu"},
        {"id": "iris"},
        {"id": "dynamic-fps"},
        {"id": "sodium"},
        {"id": "morechathistory"},
        {"id": "capes"},
        {"id": "zoomify"},
        {"id": "ferrite-core"},
        {"id": "sodium-extra"},
        {"id": "immediatelyfast"},
        {"id": "language-reload"},
        {"id": "lambdynamiclights"},
        {"id": "badoptimizations"},
        {"id": "entity-model-features"},
        {"id": "entitytexturefeatures"},
        {"id": "lighty"},
        {"id": "better-stats"},
        {"id": "music-notification"},
        {"id": "status-effect-bars"},
        {"id": "mace-but-3d"},
        {"id": "glowing-torchflower"},
        {"id": "detail-armor-bar"},
        {"id": "visuality"},
        {"id": "simple-voice-chat"},
        {"id": "chat-heads"},
        {"id": "mouse-tweaks"},
        {"id": "clientsort"},
        {"id": "bobby"},
        {"id": "fastquit"},
        {"id": "mixintrace"},
        {"id": "e4mc"},
        {"id": "modelfix"},
        {"id": "entityculling"},
        {"id": "fabrishot"},
        {"id": "controlify"},
        {"id": "lithium"},
        {"id": "appleskin"},
        {"id": "modernfix"},
        {"id": "cubes-without-borders"},
        {"id": "better-mount-hud"},
        {"id": "ebe"},
        {"id": "continuity"},
        {"id": "fabricskyboxes"},
        {"id": "fabricskyboxes-interop"},
        {"id": "noisium"},
        {"id": "litematica"},
        {"id": "shulkerboxtooltip"},
        {"id": "betterf3"},
        {"id": "eating-animation"},
        {"id": "pick-up-notifier"},
        {"id": "cherished-worlds"},
        {"id": "polytone"},
        {"id": "world-play-time"},
        {"id": "skinshuffle"},
        {"id": "no-resource-pack-warnings"},
        {"id": "infinite-music"},
        {"id": "particular"},
        {"id": "3dskinlayers"},
        {"id": "auth-me"},
        {"id": "inventory-blur"},
        {"id": "calcmod"},
        {"id": "chunky"},
        {"id": "better-f1-reborn"},
        {"id": "xaeros-world-map"},
        {"id": "xaeros-minimap"},
        {"id": "not-enough-animations"},
        {"id": "fast-ip-ping"},
        {"id": "extended-world-selection"},
        {"id": "clumps"},
        {"id": "legendary-tooltips"},
        {"id": "flashback"},
        {"id": "bettercommandblockui"},
        {"id": "improved-sign-editing"},
        {"id": "bindcommands"},
        {"id": "fallingleaves"},
        {"id": "no-chat-reports"},
        {"id": "paginatedadvancements"},
        {"id": "indium"},
        {"id": "resourcify"},
        {"id": "craftpresence"},
        {"id": "advancement-plaques"},
        {"id": "krypton"},
        {"id": "make_bubbles_pop"},
        {"id": "snapper"},
        {"id": "seamless-loading-screen"},
        {"id": "screenshot-to-clipboard"},
        {"id": "chunks-fade-in"},
        {"id": "optigui"},
        {"id": "custom-credits"},
        {"id": "dynamiccrosshair"},
        {"id": "show-me-your-skin"},
        {"id": "controlling"},
        {"id": "durability-plus"},
        {"id": "hey-wiki"},
        {"id": "sound-controller"},
        {"id": "debugify"},
        {"id": "my-resource-pack"}],
    "shaderpacks": [
        {"id": "makeup-ultra-fast-shaders"},
        {"id": "miniature-shader"},
        {"id": "solas-shader"},
        {"id": "rethinking-voxels"},
        {"id": "complementary-unbound"},
        {"id": "bsl-shaders"},
        {"id": "complementary-reimagined"},
        {"id": "bliss-shader"}],
    "resourcepacks": [
        {"id": "default-splashes"},
        {"id": "fullbright-ub"},
        {"id": "fresh-animations"},
        {"id": "visual-armor-trims"},
        {"id": "icons"},
        {"id": "better-flame-particles"},
        {"id": "simple-grass-flowers"},
        {"id": "mob-crates"},
        {"id": "fancy-crops"},
        {"id": "qraftys-capitalized-font"},
        {"id": "enchant-icons-countxd"},
        {"id": "even-better-enchants"},
        {"id": "cubic-sun-moon"},
        {"id": "redstone-tweaks"},
        {"id": "low-on-fire"},
        {"id": "fresh-player-animations"},
        {"id": "better-leaves"},
        {"id": "3d-plants"},
        {"id": "spectral"},
        {"id": "reimagined"},
        {"id": "hyper-realistic-sky"},
        {"id": "grimdark-sky"},
        {"id": "animated-items"},
        {"id": "better-lanterns"},
        {"id": "dramatic-skys"},
        {"id": "new-glowing-ores"},
        {"id": "bow-load-indicator"},
        {"id": "chat-reporting-helper"},
        {"id": "spryzeens-knight-armor"},
        {"id": "spryzeens-healthbars"},
        {"id": "colourful-containers-gui"},
        {"id": "colourful-containers-dark-mode-gui"},
        {"id": "translations-for-sodium"},
        {"id": "spawned-eggs"},
        {"id": "icons-advertisement-removal"}]
}
