name = "Client+"
author = "Thijzert"
version = "1.0.0+1.20.1-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c2e1b556f9b231f6a918426da8acbc733ca6ca19141781bbea24c43065e7d84"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
