name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.4-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f83e67981aec7aad1e3b983fbcf730d1e21f502f41180d8777afff2d141d396"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
