name = "Client+"
author = "Thijzert"
version = "1.1.0+1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01127858c3acb6e882a0f2ffdc5f733963baec62aa6a0c5fe2b8c0c2ce80ad3e"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
