name = "Client+"
author = "Thijzert"
version = "2.0.0+1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d7f4f17073267bb028fd08a219c42584fcceee5fe77a39be858233bef6b077a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
