name = "Client+"
author = "Thijzert"
version = "1.2.0+1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ff552a6b346af83d1d1a1a87e178a67acc0421ca332a6c9970ca72f326c18f2"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
