name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.4-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b968f87b43ccc3a79da8a943a8e43992caf5eeb7d15f029dfffdecfbe4d3ada9"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
