name = "Client+"
author = "Thijzert"
version = "1.0.1+1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3abed0abf509ffa256025bc40846234a7b67849d8bd1f678900cb15d26bb0639"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
