name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.4-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7321aec14857d33587ce8339595a57e3ca34039a3355d3d2864a03d0011fbb8d"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
