name = "Client+"
author = "Thijzert"
version = "2.0.0+1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bff5cb2ff091baa4a8b64daf0878463ad19cdb32af6b95748ac5ecc6003e29ba"

[versions]
fabric = "0.16.13"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
