name = "Client+"
author = "Thijzert"
version = "2.0.0+1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7980645881b65e3cd4420a4d82c265302068773c821c1bdf1dd7415b214fffa"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
