name = "Client+"
author = "Thijzert"
version = "2.0.0+1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c10fd19e566e97c33d2ae1f831e1f050644dd87984fee8b3107c4db40cd1388d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
