name = "Client+"
author = "Thijzert"
version = "1.2.0+1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0fad7f92983be08505c1098a63234cb3aaebf4b1b4fba3fb22413b6ed379dba"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
