name = "Client+"
author = "Thijzert"
version = "1.2.0+1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21743ee8df3ae81048d96f86479ac6c517a96481f3430272fa42eea184fcd7df"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
