name = "Client+"
author = "Thijzert"
version = "2.0.1+1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "555e4f67f5dd43d83f426e6015f621bd6aa13e4d847d04c84bcd4cf31d1367ed"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
