name = "Client+"
author = "Thijzert"
version = "1.0.0+1.20.4-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "492397689a29111843c50b059d2950bce4f8cd8bc2bd2926750725784fa9dc09"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
