name = "Client+"
author = "Thijzert"
version = "1.0.0+1.20.4-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2abe0bec8c97ae9242c8fff1ce3fec70384ffd31651a40debe974d975d19d9f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
