# Don't change this! Version used to track needed updates.
version = 0
biomeColorRain = true
biomeParticlesRadius = 32
mushroomSporeBiomes = [
    "minecraft:mushroom_fields"
]
mushroomSporeDensity = 10
fireflyBiomes = [
    "minecraft:swamp",
    "minecraft:mangrove_swamp"
]
fireflyDensity = 6
pollenBiomes = [  ]
pollenDensity = 30
sculkDustBiomes = [
    "minecraft:deep_dark"
]
sculkDustDensity = 5