name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.3-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b2e0ed70f96b1a2d8a8be13ddacb0e1bd4f699462c194cc7ea22e24ae733dfd"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
