name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.3-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8f75a516d1d47577faf2d628ef1372064961b3e9ec6e6e0e35b412f2da214cb"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
