name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.3-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd5f2034784fb504930da3d797062415a3964c8b3e7b85ac300e208850f4e1d4"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
