name = "Client+"
author = "Thijzert"
version = "1.2.0+1.21.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69f7d775eebcb09083f793d924c1fabe7ccc362bfba48a26d8531e552d33f87a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
