name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.3-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c0546872b3f036277fdd5cf6a1bf41e5121fd729680a6fde5d4c7166633dc02"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
