name = "Client+"
author = "Thijzert"
version = "1.2.0+1.21.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3379c1ef865ad3648d75cfaa644a05d86c43a21109eab2cc7d01926ccefb931c"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
