name = "Client+"
author = "Thijzert"
version = "1.1.0+1.21.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05d8acf60bf95ae8a6fd4d9959d9ebd2dc6cca967e97a80051a0a3498bbe94da"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
