name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.3-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "118fa5e34fe9430f01e592b6bee60d76832a94f583f4bcde53c0b0c2e1c2b28c"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
