name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.3-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6baf57164d193ef588729538bfb37ad51e304a0bc6133aabb66ecc87bf48014c"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
