name = "Client+"
author = "Thijzert"
version = "1.1.0+1.21.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdb1b2fabb13100a7a30059353097e6c50ef293923a9e52c74360cf50608cd48"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
