name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.3-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f4bbbe260b6bd85742f04afe42409b47838864586a2d774be022aa3ce37d04c"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
