name = "Client+"
author = "Thijzert"
version = "1.2.0+1.21.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff878da6ccbe1693ccdb8e15ee96daafeba0c1e69feade543bc501762ed6b296"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
