name = "Client+"
author = "Thijzert"
version = "1.1.0+1.21.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2e2aa121aa0cd0ac591a0c55a777562872030126c58b8f46434cc90b3dc6522"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
